# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InstronCSVFileHandler.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InstronCSVHandler(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(422, 305)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.PB_SelectCSVFile = QtWidgets.QPushButton(Form)
        self.PB_SelectCSVFile.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_SelectCSVFile.sizePolicy().hasHeightForWidth())
        self.PB_SelectCSVFile.setSizePolicy(sizePolicy)
        self.PB_SelectCSVFile.setMinimumSize(QtCore.QSize(0, 42))
        self.PB_SelectCSVFile.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.PB_SelectCSVFile.setFont(font)
        self.PB_SelectCSVFile.setObjectName("PB_SelectCSVFile")
        self.gridLayout.addWidget(self.PB_SelectCSVFile, 2, 0, 1, 1)
        self.LB_Text = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_Text.sizePolicy().hasHeightForWidth())
        self.LB_Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.LB_Text.setFont(font)
        self.LB_Text.setObjectName("LB_Text")
        self.gridLayout.addWidget(self.LB_Text, 0, 0, 1, 1)
        self.LB_CurrentFile = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_CurrentFile.sizePolicy().hasHeightForWidth())
        self.LB_CurrentFile.setSizePolicy(sizePolicy)
        self.LB_CurrentFile.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.LB_CurrentFile.setFont(font)
        self.LB_CurrentFile.setObjectName("LB_CurrentFile")
        self.gridLayout.addWidget(self.LB_CurrentFile, 1, 0, 1, 1)
        self.HL_Buttons = QtWidgets.QHBoxLayout()
        self.HL_Buttons.setContentsMargins(30, 15, 30, 15)
        self.HL_Buttons.setSpacing(20)
        self.HL_Buttons.setObjectName("HL_Buttons")
        self.PB_Apply = QtWidgets.QPushButton(Form)
        self.PB_Apply.setMinimumSize(QtCore.QSize(80, 28))
        self.PB_Apply.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.PB_Apply.setFont(font)
        self.PB_Apply.setObjectName("PB_Apply")
        self.HL_Buttons.addWidget(self.PB_Apply)
        self.PB_Cancle = QtWidgets.QPushButton(Form)
        self.PB_Cancle.setMinimumSize(QtCore.QSize(80, 28))
        self.PB_Cancle.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.PB_Cancle.setFont(font)
        self.PB_Cancle.setObjectName("PB_Cancle")
        self.HL_Buttons.addWidget(self.PB_Cancle)
        self.gridLayout.addLayout(self.HL_Buttons, 3, 0, 1, 1)

        self.PB_SelectCSVFile.clicked.connect(Form.handleSelectCSVFile)
        self.PB_Apply.clicked.connect(Form.handleApply)
        self.PB_Cancle.clicked.connect(Form.close)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PB_SelectCSVFile.setText(_translate("Form", "Select a CSV File"))
        self.LB_Text.setText(_translate("Form", "Current File:"))
        self.LB_CurrentFile.setText(_translate("Form", "No Select"))
        self.PB_Apply.setText(_translate("Form", "Apply"))
        self.PB_Cancle.setText(_translate("Form", "Cancle"))
